using System;
using System.Collections.Generic;
using System.Linq;
using JRodrigoAV.Sitio.Models.Cards;

namespace JRodrigoAV.Sitio.Models.Decks
{
    public partial class BlackDeck
    {
        public BlackDeck()
        {
            AllCards = new List<BlackCard>() { };
            int id = 1;
            string[] cards = new string[] {
                "(Heavy breathing) Luke, I am __________.",
                "\"Watson!\" Holmes exclaimed, \"This man was obviously killed by __________!\"",
                "__________ + __________ = __________.",
                "__________ ain't nothin' to fuck with.",
                "__________ be all like __________.",
                "__________ gives a whole new meaning to __________.",
                "__________ good to the last drop.",
                "__________ in the front seat; __________ in the back seat; gotta make my mind up, which seat can I take?",
                "__________ in the morning, sailors take warning.",
                "__________ is a classic case of __________.",
                "__________ is a gateway to __________.",
                "__________ is a slippery slope that leads to __________.",
                "__________ is a time-saving godsend for busy housewives.",
                "__________ is best enjoyed on the first date.",
                "__________ is dead to me.",
                "__________ is nothing __________ can't fix.",
                "__________ is now outsourced to call centers in India.",
                "__________ is the name of my new indie black metal emo jazz post-dubstep funk band.",
                "__________ is the new black.",
                "__________ is the root of all evil.",
                "__________ is way better in __________ mode.",
                "__________ isn't about sex, it's about power.",
                "__________ may pass, but __________ will last forever.",
                "__________ means never having to say you're sorry.",
                "__________ R Us.",
                "__________ will never be the same after __________.",
                "__________ would be woefully incomplete without __________.",
                "__________, for the win!",
                "__________, fun for the whole family!",
                "__________. Achievement unlocked.",
                "__________. Awesome in theory, kind of a mess in practice.",
                "__________. Because, fuck you, that's why.",
                "__________. Betcha can't have just one!",
                "__________. High five, bro.",
                "__________. Hours of fun. Easy to use. Perfect for __________.",
                "__________. I'd hit that.",
                "__________. It's a trap!",
                "__________. It's everywhere you want to be.",
                "__________. That was so metal.",
                "__________. That's how I want to die.",
                "__________. The Care Bear Stare",
                "__________. The Final Frontier.",
                "__________. The Nicolas Cage Story",
                "__________. The other white meat.",
                "__________: Good to the last drop.",
                "__________: Hours of fun. Easy to use. Perfect for __________!",
                "__________: Kid-tested, mother-approved.",
                "__________: The Other White Meat.",
                "“This is madness!” “No. THIS IS __________!”",
                "2 AM in the city that never sleeps. The door swings open and *she* walks in, legs up to here. Something in her eyes tells me she's looking for __________.",
                "2 things you need to survive on a deserted island",
                "9 out of 10 doctors agree, __________ twice a day prevents cancer.",
                "A fortune teller told me I will live a life filled with __________.",
                "A hot new alternative medical practice involves placing __________ in __________.",
                "A little-known fact is that Microsoft Windows was originally slated to be the first operating system to include __________.",
                "A little-known provision of Obamacare allows __________ access to __________.",
                "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to __________.",
                "A remarkable new study shows that chimps have evolved their own primitive version of __________.",
                "A romantic, candlelit dinner would be incomplete without __________.",
                "A study published in Nature this week found that __________ is good for you in small doses. ",
                "A study published in Nature this week found that __________ is good for you in small doses.",
                "A successful job interview begins with a firm handshake and ends with __________.",
                "According to an old Romanian superstition, __________ will happen if you Don't __________ before going to bed.",
                "According to Freud, all children progress through three stages of development: the oral stage, the anal stage, and the __________ stage.",
                "Adventure. Romance. __________. From Paramount Pictures, '__________.' ",
                "After Billy Mays died, he sold God __________.",
                "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: __________.",
                "After months of debate, the Occupy Wall Street General Assembly could only agree on \"More __________!\"",
                "After months of practice with __________, I think I'm finally ready for __________.",
                "After the earthquake, Sean Penn brought __________ to the people of Haiti.",
                "All the cool kids are doing it.",
                "Alternative medicine is now embracing the curative powers of __________.",
                "An international tribunal has found __________ guilty of __________.",
                "And I would have gotten away with it, too, if it hadn't been for __________.",
                "And in the end, the dragon was not evil; he just wanted __________.",
                "And on his farm he had __________, e-i-e-i-o!",
                "And the Academy Award for __________ goes to __________.",
                "And then little Billy woke up the next morning, he discovered that the tooth fairy had left __________ under his pillow.",
                "And today's soup is Cream of __________.",
                "And what did you bring for show and tell?",
                "And would you like those buffalo wings mild, hot, or __________?",
                "Apple has revealed they now have a patent for __________.",
                "Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with __________: priceless.",
                "Art isn't just a painting in a stuffy museum. Art is alive. Art is __________.",
                "As King, how will I keep the peasants in line?",
                "As part of his contract, Prince won't perform without __________ in his dressing room.",
                "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for __________.",
                "As reparations for slavery, all African Americans will receive __________.",
                "As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and __________.",
                "Ask your doctor if __________ is right for you.",
                "Aw babe, your burps smell like __________.",
                "Awww, sick! I just saw this skater do a 720 kickflip into __________.",
                "Back in my day, __________ only cost a nickel.",
                "Bang __________ Marry __________ Kill __________.",
                "Before __________, all we had was __________.",
                "Before I run for president, I must destroy all evidence of my involvement with __________.",
                "Behind every powerful man is __________.",
                "Best you go back where you came from, now. We don't take too kindly to __________ in these parts.",
                "But before I kill you, Mr. Bond, I must show you __________.",
                "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate __________ in the workplace.",
                "Can't you see? The Jews are behind everything -- the banks, the media, even __________!",
                "Charades was ruined for me forever when my mom had to act out __________.",
                "Check your privilege. And __________.",
                "Chili's special tonight: __________ with a side of __________.",
                "Choosy moms choose __________.",
                "Cirque de Soleil presents MYSTIQUEE, a night of daring acrobatics, whimsy and __________.",
                "CNN breaking news! Scientists discover __________.",
                "Come to Dubai, where you can relax in our world-famous spas, experience the nightlife, or simply enjoy __________ by the poolside.",
                "Coming to Broadway next season: __________ on the Roof.",
                "Coming to Broadway this season, __________: The Musical.",
                "Coming to Red Lobster this month, __________.",
                "Computer! Display __________ on screen. Enhance.",
                "Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we can offer you __________.",
                "Critics are raving about HBO's new Game of Thrones spin-off, '__________ of __________.'",
                "Daddy drinks because of __________.",
                "Daddy, why is mommy crying?",
                "Dammit, Gary. You can't just solve every problem with __________.",
                "Damn it feels good to be __________.",
                "Dance like there's nobody watching, love like you'll never be hurt, and live like you're __________.",
                "Danger! __________ ahead!",
                "Dear Abby, I'm having some trouble with __________ and would like your advice.",
                "Dear Leader Kim Jong Un, our village praises your infinite wisdom with a humble offering of __________.",
                "Dear Sir or Madam, We regret to inform you that the Office of __________ has denied your request for __________.",
                "Disney presents __________ on ice!",
                "Disney's newest Pixar movie will be about __________.",
                "Do not fuck with me! I am literally __________ right now.",
                "Do the Dew with our most extreme flavor yet! Get ready for Mountain Dew __________!",
                "Do you lack energy? Does it sometimes feel like the whole world is __________? Ask your doctor about Zoloft.",
                "Doctor, you've gone too far! The human body wasn't meant to withstand that amount of __________.",
                "Don't worry, kid. It gets better. I've been living with __________ for 20 years.",
                "Don't forget! Beginning this week, Casual Friday will officially become '__________ Friday.'",
                "Don't miss Rachel Ray's hit new show, Cooking with __________.",
                "Don't miss the action comedy of the year! One cop plays by the book. The other's only interested in one thing: __________.",
                "Don't worry, Penny! Go Go Gadget __________!",
                "During high school I never really fit in until I found __________ club.",
                "During high school, I never really fit in until I found __________ club.",
                "During his midlife crisis, my dad got really into __________.",
                "During sex, I like to think about __________.",
                "Errbody in the club __________.",
                "Every __________ should be required to get a tattoo of __________.",
                "Every step towards __________ gets me a little bit closer to __________.",
                "Everybody join hands and close your eyes. Do you sense that? That's the presence of __________ in this room.",
                "Everyone down on the ground! We don't want to hurt anyone. We're just here for __________.",
                "Excuse me, waiter. Could you take this back? This soup tastes like __________.",
                "Fear leads to anger. Anger leads to hate. Hate leads to __________.",
                "Feeling so grateful! #amazing #mylife #__________",
                "Finally! A service that delivers __________ right to your door.",
                "For campaign funding reform to really be effective, there needs to be a specific policy about __________ contributions.",
                "For my next trick, I will pull __________ out of __________.",
                "Forget everything you know about __________, because now we've supercharged it with __________.",
                "Fred Phelps and his church have just announced that they plan to start picketing the funerals of __________ as well as gays.",
                "Fun tip! When your man asks you to go down on him, try surprising him with __________ instead.",
                "Future historians will agree that __________ marked the beginning of America's decline.",
                "Genius is 10% inspiration and 90% __________.",
                "Girls just wanna have __________.",
                "Give me liberty, or give me __________!",
                "Go-go Gadget __________!",
                "Google Calendar alert: __________ in 10 minutes.",
                "Groundbreaking research provides convincing evidence that __________ killed the dinosaurs.",
                "Happiness is __________.",
                "Having problems with __________? Try __________!",
                "Having problems with __________? Try __________.",
                "Having the worst day EVER. #__________",
                "Having tired of poetry and music, the immortal elves now fill their days with __________.",
                "Heed my voice, mortals! I am the god of __________, and I will not tolerate __________.",
                "Help me doctor, I've got __________ in my butt!",
                "Here at the Academy for Gifted Children, we allow students to explore __________ at their own pace.",
                "Here is the church / Here is the steeple / Open the doors / And there is __________.",
                "Here is the church. Here is the steeple. Open the doors and there is __________.",
                "Hey baby, come back to my place and I'll show you __________.",
                "Hey Reddit! I'm __________. Ask me anything.",
                "Hey Rocky, watch me pull __________ out of my __________!",
                "Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about __________!",
                "Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about __________.",
                "Hi MTV! My name is Kendra, I live in Malibu, I'm into __________, and I love to have a good time.",
                "Hi, this is Jim from accounting. We noticed a $1,200 charge labeled '__________.' Can you explain?",
                "Honey, I have a new roleplay I want to try tonight! You can be __________, and I'll be __________.",
                "Horton could hear it through the bedroom wall...his mother and __________.",
                "Horton is always forcing his __________ on other people.",
                "How am I compensating for my tiny penis?",
                "How am I maintaining my relationship status?",
                "How are the writers of Cards Against Humanity spending your $25?",
                "How did I lose my virginity?",
                "How did I lose my virgitnity?",
                "How did this __________ get into my __________?",
                "I always call in sick to work when I have a bad case of __________.",
                "I always think of __________ when I fall asleep.",
                "I am become __________, destroyer of __________.",
                "I can drive and __________ and __________ at the same time.",
                "I can handle public displays of affection, but __________ is really too much.",
                "I can't get no __________.",
                "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
                "I don't believe in God. I believe in __________.",
                "I don't mean to brag, but they call me the Michael Jordan of __________.",
                "I drink to forget __________.",
                "I feel the need—the need for __________.",
                "I firmly believe that for the economy to recover, the Department of __________ needs to change its policies on __________.",
                "I for one welcome our new __________ overlords!",
                "I get by with a little help from __________.",
                "I got 99 problems but __________ ain't one.",
                "I got a fever and the only cure is more __________.",
                "I have a strict policy. First date, dinner. Second date, kiss. Third date, __________.",
                "I have decided to commit to a life of studious contemplation on __________.",
                "I learned the hard way that you can't cheer up a grieving friend with __________.",
                "I like my women like __________.",
                "I like to keep __________ as a souvenir of my sexual encounters.",
                "I live my life according to the teachings of __________.",
                "I love __________ in my __________.",
                "I love the smell of __________ in the morning.",
                "I may not be much to look at, but I fuck like __________.",
                "I met my current significant other at __________,",
                "I might be a __________, but at least I'm no __________.",
                "I need you like __________ needs __________.",
                "I never truly understood __________ until I encountered __________.",
                "I really hate __________ at work. So I take care of it with __________.",
                "I sleep like a baby after bathing in a tub full of __________.",
                "I spent my whole life working toward __________ only to have it ruined by __________.",
                "I spent my whole life working toward __________, only to have it ruined by __________.",
                "I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like __________.",
                "I want to go to school to study __________.",
                "I was into __________ before it was cool.",
                "I went from __________ to __________, all thanks to __________.",
                "I went to the desert and ate of the peyote cactus. Turns out my spirit animal is __________.",
                "I will not eat them Sam-I-Am. I will not eat __________.",
                "I work my ass off all day for this family, and this is what I come home to? __________!?",
                "I work my ass off all day for this family, and this what I come home to? __________!?",
                "I work out so that I can look good when I'm __________.",
                "ï¿¼Believe it or not, Jim Carrey can do a dead-on impression of __________.",
                "ï¿¼How did Stella get her groove back?",
                "ï¿¼I'm a bitch, I'm a lover, I'm a child, I'm __________.",
                "ï¿¼It's Morphin' Time! Mastodon! Pterodactyl! Triceratops! Sabertooth Tiger! __________!",
                "ï¿¼Siskel and Ebert have panned __________ as 'poorly conceived' and 'sloppily executed.'",
                "ï¿¼Tonight on SNICK: 'Are You Afraid of __________?'",
                "ï¿¼Up next on Nickelodeon: 'Clarissa Explains __________.'",
                "I'm Miss Tennessee, and if I could make the world better by changing one thing, I would get rid of __________.",
                "I'm not like the rest of you. I'm too rich and busy for __________.",
                "I'm sorry, Mrs. Chen, but there was nothing we could do. At 4:15 this morning, your son succumbed to __________.",
                "I'd rather be __________.",
                "If a pot of gold is on one end of the rainbow, what is on the other?",
                "If at first you don't succeed, try __________.",
                "If God didn't want us to enjoy __________, he wouldn't have given us __________.",
                "If I don't enjoy __________, then the terrorists win.",
                "If I weren't so busy with __________, I'd be __________.",
                "If there's one thing you could change about me it would be __________.",
                "If you can't handle __________, you'd better stay away from __________.",
                "If you had to describe me, the Card Czar, using only one of the cards in your hand, which one would it be?",
                "I'll take the BBQ bacon burger with a fried egg and fuck it how about __________.",
                "I'm Bobby Flay, and if you can't stand __________, get out of the kitchen!",
                "I'm going on a cleanse this week. Nothing but kale juice and __________.",
                "I'm having trouble finding a college which will allow me to pursue a degree in __________.",
                "I'm just gonna stay in tonight. You know, Netflix and __________.",
                "I'm pretty sure I'm high right now, because I'm absolutely mesmerized by __________.",
                "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
                "I'm sorry, sir, but we don't allow __________ at the country club.",
                "I'm sorry, sir, but your insurance plan doesn't cover injuries caused by __________.",
                "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
                "In a pinch, __________ can be a suitable substitute for __________.",
                "In a surprising turnaround, __________ has publicly come out as supporting President Obama.",
                "In a world ravaged by __________, our only solace is __________.",
                "In an astonishing and ground-breaking decision, the Supreme Court has decided in favor of __________.",
                "In an attempt to recreate conditions just after the Big Bang, physicists at the LHC are observing collisions between __________ and __________.",
                "In his farewell address, George Washington famously warned Americans about the dangers of __________.",
                "In his new action comedy, Jackie Chan must fend off ninjas while also dealing with __________.",
                "In his new self-produced album, Kanye West raps over the sounds of __________.",
                "In his newest and most difficult stunt, David Blaine must escape from __________.",
                "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________.",
                "In L.A. County Jail, word is you can trade 200 cigarettes for __________.",
                "In line with our predictions, we find a robust correlation between __________ and __________ (p<.05).",
                "In line with our predictions, we find a robust correlation between __________ and __________.",
                "In M. Night Shyamalan's new movie, Bruce Willis discovers that __________ had really been __________ all along.",
                "In Nintendo's new game, you must fight off wave after wave of __________ in order to save __________.",
                "In return for my soul, the Devil promime __________, but all I got was __________.",
                "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.",
                "In the 1950s, psychologists prescribed __________ as a cure for homosexuality.",
                "In the beginning, there was __________. And the Lord said 'Let there be __________.'",
                "In the grim darkness of the future there is only __________.",
                "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time.",
                "In the new tenth circle of Hell, sinners will be condemned to an eternity of __________.",
                "In the seventh circle of Hell, sinners must endure __________ for all eternity.",
                "In what's being hailed as a major breakthrough, scientists have synthesized __________ in the lab.",
                "Instead of coal, Santa now gives the bad children __________.",
                "Instead of endorsing Jell-O Pudding Pops, Bill Cosby now endorses __________.",
                "Instead of her normal self, Cinderella should have turned into __________ at midnight.",
                "Instead of Robin, Batman should have had __________ as a sidekick.",
                "Instead of the Jews, Hitler should have worried more about __________.",
                "Introducing the amazing superhero/sidekick duo! It's __________ and __________!",
                "Introducing the amazing superhero/sidekick duo! It's __________ and __________.",
                "Introducing Xtreme Baseball! It's like baseball, but with __________!",
                "Iron Chef: Today's secret ingredient is __________.",
                "It is often argued that our ancestors would have never evolved without the aid of __________.",
                "It lurks in the night. It hungers for flesh. This summer, no one is safe from __________.",
                "It rubs __________ on its skin or else it gets __________ again.",
                "It sucks when you look in the fridge, and all you have to eat is __________.",
                "It was more uncomfortable than __________ at a __________ convention.",
                "It's a pity that kids these days are all getting involved with __________.",
                "It's not delivery. It's __________.",
                "I've got rhythm, I've got music, I've got __________. Who could ask for anything more?",
                "I've got the fever and the only cure is more __________.",
                "I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw __________.",
                "James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: __________.",
                "Jesus is __________.",
                "Just saw this upsetting video! Please retweet!! #stop__________",
                "Keep your friends close, but your __________ closer.",
                "Kids, I don't need drugs to get high. I'm on high on __________.",
                "Kitten thinks of nothing but __________ all day.",
                "Legend of Zelda: The __________ of __________.",
                "Legend tells of a princess who has been asleep for a thousand years and can only be awoken by __________.",
                "Life for American Indians was forever changed when the White Man introduced them to __________.",
                "Life's pretty tough in the fast lane. That's why I never leave the house without __________.",
                "Lifetime presents '__________, the Story of __________.' ",
                "Lifetime® presents \"__________ the Story of __________.\"",
                "Like a good neighbor __________ is there.",
                "Listen, Gary, I like you. But if you want that corner office, you're going to have to show me __________.",
                "Listen, son. If you want to get involved with __________, I won't stop you. Just steer clear of __________.",
                "Little Miss Muffet / Sat on a tuffet / Eating her curds and __________.",
                "Little Miss Muffet Sat on a tuffet, Eating her curds and __________.",
                "Looking to earn some big bucks? Learn how to make __________ work for you!",
                "Lovin' you is easy 'cause you're __________.",
                "Loving you is easy 'cause you're __________.",
                "LSD + __________ = really bad time.",
                "Madam President, the asteroid is headed directly for Earth and there's only one thing that can stop it: __________.",
                "Make a haiku.",
                "Man, this is bullshit. Fuck __________.",
                "Maybe she's born with it. Maybe it's __________.",
                "Members of New York's social elite are paying thousands of dollars just to experience __________.",
                "Michael Bay's new three-hour action epic pits __________ against __________.",
                "Mister Owl, how many licks does it take to get to the center of __________?",
                "Mom's to-do list: buy groceries, clean up __________, soccer practice.",
                "Money can't buy me love, but it can buy me __________.",
                "Moral at work was boosted when they put __________ in the vending machines.",
                "Most Americans would not vote for a candidate who is openly __________.",
                "Mr. Owl, how many licks does it take to get to the center of __________?",
                "MTV's new reality show features eight washed-up celebrities living with __________.",
                "My country, 'tis of thee, sweet land of __________.",
                "My favorite book is the classic tale of __________, written by __________.",
                "My favorite childhood memory is__________.",
                "My favorite TV channel is the one that shows programs about __________.",
                "My favourite family recipe is __________ and __________ with just a dash of __________.",
                "My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and __________.",
                "My gym teacher got fired for adding __________ to the obstacle course.",
                "My life is ruled by a vicious cycle of __________ and __________.",
                "My Little Pony: Friendship is __________.",
                "My mission in life is to create a videogame about __________.",
                "My mom freaked out when she looked at my browser history and found __________.com/__________.",
                "My new favorite porn star is Joey \"__________\" McGee.",
                "My new favorite porn star is Joey '__________' McGee.",
                "My other car is a __________.",
                "My plan for world domination begins with __________.",
                "New car sticker craze: Calvin pissing on __________.",
                "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
                "Next on ESPN2, the World Series of __________.",
                "Next on ESPN2: The World Series of __________.",
                "Next on Oprah, teens addicted to __________.",
                "Next time on Dr. Phil: How to talk to your child about __________.",
                "Next week on the Discovery Channel, one man must survive in the depths of the Amazon with only __________ and his wits.",
                "Next, on Martha Stewart's Living, spruce up your __________ with __________.",
                "Next, on the Twilight Zone: a parallel universe in which every instance of __________ is replaced by __________.",
                "No, no, no, no, no, no, NO! I will NOT let __________ ruin this wedding.",
                "Nobody puts __________ in a corner.",
                "Nothing beats cuddling with __________ in bed.",
                "Nothing feels better than __________ on __________.",
                "Nothing says 'I love you' like __________.",
                "Now at the Smithsonian: an interactive exhibit on __________.",
                "Now in bookstores: 'The Audacity of __________,' by Barack Obama.",
                "Now on Neflix: Jiro Dreams of __________.",
                "Now witness the firepower of this fully armed and operational __________!",
                "Oh no! Siri, how do I fix __________?",
                "Oh, your daughter should meet my son! He gives to charity, he loves __________, and did I mention he's a doctor?",
                "On tonight's special report, __________. Fact or fiction?",
                "One day a man is bitten by __________ and is transformed into __________.",
                "One more thing. Watch out for Big Mike. They say he killed a man with __________.",
                "Only __________ is worse than a heretic.",
                "Only two things in life are certain: death and __________.",
                "Ooo, daddy like __________.",
                "Oprah's book of the month is '__________ For __________: A story of hope.' ",
                "Our most powerful weapon on the day of the zombie apocalypse will be __________.",
                "Patient presents with __________. Likely a result of __________.",
                "Poor Brandon, still living in his parent's basement. I heard he never got over __________.",
                "Press [DOWN DOWN LEFT RIGHT B] to unleash __________.",
                "Puberty is a time of change. You might notice hair growing in new places. You might develop an interest in __________. This is normal.",
                "Remember, __________ is never funny. Unless it involves __________.",
                "Roses are red; Violets are __________; __________ is __________, and so are you.",
                "Run, run, as fast as you can! You can't catch me, I'm __________!",
                "Say no to __________.",
                "Science has discovered that beyond the edges of the universe, there is only __________.",
                "Science will never explain __________.",
                "Scientists have reverse engineered alien technology that unlocks the secrets of __________.",
                "She's a lady in the streets, __________ in the sheets.",
                "She's just one of the guys, you know? She likes beer, and football, and __________.",
                "She's up all night for good fun. I'm up all night for __________.",
                "Sizzler's special tonight: __________ with a side of __________.",
                "Something you should regret, but secretly don't.",
                "Sometimes you feel like __________, sometimes you don't.",
                "Son, take it from someone who's been around the block a few times. Nothin' puts her in the mood like __________.",
                "Step 1: __________. Step 2: __________. Step 3: Profit.",
                "Step 1: __________. Step 2:__________. Step 3: Profit.",
                "Sticks and stones may break my bones, but __________ will never hurt me.",
                "Stop staring at my __________.",
                "Such __________. Very __________. Wow.",
                "Summer lovin', had me a blast. __________, happened so fast.",
                "That's right, I killed __________. How, you ask? __________.",
                "The 1930's is often regarded as the golden age of __________.",
                "The best Christmas present my grandma ever gave me was __________.",
                "The best part of waking up is __________ in your cup.",
                "The best things in life come in __________.",
                "The blind date was going horribly until we discovered our shared interest in __________.",
                "The Christian Coalition has recently decided that an even worse sin than same-sex marriage is __________.",
                "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.",
                "The class field trip was completely ruined by __________.",
                "The clown made all the children laugh with his balloon animal in the shape of __________.",
                "The Five Stages of Grief: denial, anger, bargaining, __________, acceptance.",
                "The healing process began when I joined a support group for victims of __________.",
                "The Himalayas are filled with many perils, such as __________.",
                "The internet was invented for __________.",
                "The Japanese government spent billions of yen researching __________.",
                "The Japanese have developed a smaller, more efficient version of __________.",
                "The local experimental college is now offering a course on __________ led by __________.",
                "The new Chevy Tahoe. With the power and space to take __________ everywhere you go.",
                "The new hip trend at craft bars is vodka infused with __________.",
                "The new Nintendo will be called the __________.",
                "The new version of Dungeons and Dragons makes __________ a playable race.",
                "The next ice cream flavor from Ben & Jerry's.",
                "The next Team Fortress 2 update will include __________.",
                "The only problem with __________ is that there isn't enough __________ in it.",
                "The power of love is useless against __________.",
                "The road to success is paved with __________.",
                "The sad truth is, at the edge of the universe, there is nothing but __________.",
                "The secret to a lasting marriage is communication, communication, and __________.",
                "The six things I could never do without: oxygen, facebook, chocolate, netflix, friends, and __________ LOL!",
                "The Smithsonian Museum of Natural History has just opened an interactive exhibit on __________.",
                "The sound of your life, __________ radio!",
                "The theme for our senior prom will be __________.",
                "The top Google autocomplete results for Barack Obama: Barack Obama height. Barack Obama net worth. Barack Obama __________.",
                "The votes are in, and the new high school mascot is __________.",
                "The world is going to end when __________ falls on the Earth and __________ will be everywhere.",
                "Then the princess kissed the frog, and all of a sudden the frog was __________!",
                "There is a time for peace, a time for war, and a time for __________.",
                "There is no God. It's just __________ and then you die.",
                "There is nothing worse than seeing __________ in the light of day.",
                "There's no crying in __________.",
                "There's no such thing as __________.",
                "They found __________ in the dumpster behind the abortion clinic.",
                "They said we were crazy. They said we couldn't put __________ inside of __________. They were wrong.",
                "This app is basically Tinder, but for __________.",
                "This decade will be regarded as the golden age of __________.",
                "This Friday at the Liquid Lounge, it's __________ Night! Ladies drink free.",
                "This is America. If you don't work hard, you don't succeed. I don't care if you're black, white, purple, or __________.",
                "'This is madness!' 'No. THIS IS __________!'",
                "This is the prime of my life. I'm young, hot, and full of __________.",
                "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.",
                "This is the way the world ends\n This is the way the world ends\n Not with a bang but with __________.",
                "This is your captain speaking. Fasten your seatbelts and prepare for __________.",
                "This month's Cosmo: \"Spice up your sex life by bringing __________ into the bedroom.\"",
                "This month's Cosmo: 'Spice up your sex life by bringing __________ into the bedroom.'",
                "This Thanksgiving, I'm most thankful for __________.",
                "This won't be like negotiating with the Vogons. Humans only respond to one thing: __________.",
                "This year's hottest album is '__________' by __________.",
                "This year's Pulitzer Prize winning novel was chosen for its brilliant __________, as a metaphor for __________.",
                "To become a true Yanomamo warrior, you must prove that you can withstand __________ without crying out.",
                "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of __________.",
                "Today on Maury: \"Help! My son is __________!\"",
                "Today on Maury: 'Help! My son is __________!'",
                "Today on Mythbusters, we find out how long __________ can withstand __________.",
                "Tonight on 20/20: What you don't know about __________ could kill you.",
                "Tonight, we will have sex. And afterwards, if you'd like, a little bit of __________.",
                "TRIGGER WARNING: __________.",
                "Try walking a mile in my __________.",
                "TSA guidelines now prohibit __________ on airplanes.",
                "Turns out that __________-Man was neither the hero we needed nor wanted.",
                "Two things you need to survive on a deserted island.",
                "Uh, hey guys, I know this was my idea, but I'm having serious doubts about __________.",
                "War! What is it good for?",
                "Warning: This product contains trace amounts of __________.",
                "We do not shake with our left hands in this country. That is the hand we use for __________.",
                "We never did find __________, but along the way, we sure learned a lot about __________.",
                "Well if __________ is a crime, then lock me up!",
                "Well if __________ is good enough for __________, it's good enough for me.",
                "Well if you'll excuse me, gentlemen, I have a date with __________.",
                "Well what do you have to say for yourself, Casey? This is the third time you've been sent to the principal's office for __________.",
                "Well, shit. My eyes ain't so good, but I'll eat my own boot if that ain't __________!",
                "Wes Anderson's new film tells the story of a precocious child coming to terms with __________.",
                "What am I giving up for Lent?",
                "What am I hiding from my parents?",
                "What am I lying to my friends about?",
                "What are all those whales singing about?",
                "What are my parents hiding from me?",
                "What brought the orgy to a grinding halt?",
                "What brought the orgy to a screeching halt?",
                "What did I bring back from Mexico?",
                "What did I find in the couch cushions?",
                "What did I nickname my genitals?",
                "What did the U.S. airdrop to the children of Afghanistan?",
                "What did the US airdrop to the children of Afghanistan?",
                "What did Vin Diesel eat for dinner?",
                "What do I fear my parents will find in my sock drawer?",
                "What do I like best about my job?",
                "What do I think about when I'm having trouble getting off?",
                "What don't you want to find in your Kung Pao chicken?",
                "What ended my last relationship?",
                "What gave me aids?",
                "What gets better with age?",
                "What gives me uncontrollable gas?",
                "What goes best on toast?",
                "What has been making life difficult at the nudist colony?",
                "What helps Obama unwind?",
                "What I wouldn't give for 10 minutes alone with __________",
                "What in my past led to my current position on gun control laws?",
                "What is Batman's guilty pleasure?",
                "What is in my zombie apocalypse survival bag?",
                "What is the answer to life, the universe, and everything?",
                "What is the moral of the story?",
                "What is the only way I can achieve orgasm?",
                "What keeps me up at night?",
                "What killed my boner?",
                "What left this stain on my couch?",
                "What made my first kiss so awkward?",
                "What made Spock cry?",
                "What makes Fred Phelps hard?",
                "What makes me tingle all over?",
                "What makes the world go round?",
                "What melts in your mouth, not in your hand?",
                "What never fails to liven up the party?",
                "What really killed the dinosaurs?",
                "What sucks balls?",
                "What time is it? __________ time!",
                "What totally destroyed my asshole?",
                "What turned me into a Republican?",
                "What was Abraham Lincoln's deep, dark secret?",
                "What will always get you laid?",
                "What will be an issue in the next presidential election?",
                "What will be our last chance for salvation when our new robot overlords take over?",
                "What will be put in the time capsule to preserve humanity's memory?",
                "What will end racism once and for all?",
                "What will I bring back in time to convince people that I am a powerful wizard?",
                "What will I bring to the party?",
                "What would grandma find disturbing, yet oddly charming?",
                "What's a girl's best friend?",
                "What's a total waste of Hillary Clinton's time?",
                "What's about to take this dance floor to the next level?",
                "What's fun until it gets weird?",
                "What's George W. Bush thinking about right now?",
                "What's harshing my mellow, man?",
                "What's making things awkward in the sauna?",
                "What's my anti-drug?",
                "What's my secret power?",
                "What's my superpower?",
                "What's so important right now that you can't call your mother?",
                "What's Teach for America using to inspire inner city students to succeed?",
                "What's that smell?",
                "What's that sound?",
                "What's the gayest?",
                "What's the latest bullshit that's troubling this quaint fantasy town?",
                "What's the most emo?",
                "What's the most problematic?",
                "What's the new fad diet?",
                "What's the next Happy Meal toy?",
                "What's the next happy Meal® toy?",
                "What's the real reason that I've gathered you all here today?",
                "What's the worst that could happen?",
                "What's there a ton of in heaven?",
                "When a man and a woman love each other very much, suddenly __________.",
                "When all else fails, I can always masturbate to __________.",
                "When I am a billionaire, I shal erect a 50-foot statue to commemorate __________.",
                "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
                "When I am President of the United States, I will create the Department of __________.",
                "When I get drunk, I feel that I am an expert on __________.",
                "When I get married, our vows will include words about __________.",
                "When I pooped, what came out of my butt?",
                "When I saw your mom naked, it reminded me of __________",
                "When I was a kid we used to play Cowboys and __________.",
                "When I was a kid, we used to play Cowboys and __________.",
                "When I was tripping on acid, __________ turned into __________.",
                "When I'm alone and the room is totally dark, I like to secretly __________.",
                "When life gives you __________, make __________.",
                "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
                "When you get right down to it, __________ is just __________.",
                "When you wake up from a night of heavy drinking, you usually regret __________",
                "Where do babies come from?",
                "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
                "White people like __________.",
                "Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?",
                "Who could have guessed that the alien invasion would be easily thwarted by __________.",
                "Who was my childhood hero?",
                "WHOOO! God damn I love __________!",
                "Why am I broke?",
                "Why am I in such a bad mood?",
                "Why am I laughing and crying and taking off my clothes?",
                "Why am I like this?",
                "Why am I sticky?",
                "Why are we wearing tuxedos?",
                "Why can't I sleep at night?",
                "Why did the __________ have to __________?",
                "Why do I hurt all over?",
                "Why does God pee on us, periodically?",
                "Why is mom calling?",
                "Why was my application to work at McDonald's rejected?",
                "Why won't you make love to me anymore? Is it __________?",
                "With a one-time gift of just $10, you can save this child from __________.",
                "With enough time and pressure, __________ will turn into __________.",
                "With the Democrats and Republicans in a dead heat, the election was stolen by the __________ party.",
                "Wonder Twin powers, activate! Shape of __________. Form of __________.",
                "Y'all ready to get this thing started? I'm Nick Cannon, and this is America's Got __________.",
                "Yo' mama so fat she __________!",
                "You are not alone. Millions of Americans struggle with __________ every day.",
                "You can never have too many __________ when in East LA.",
                "You can never have too much __________.",
                "You guys, you can buy __________ on the dark web.",
                "You have violated the Prime Directive! You exposed an alien culture to __________ before they were ready.",
                "You haven't truly lived until you've experienced __________ and __________ at the same time.",
                "You know God hates you when __________.",
                "You know who else liked __________? Hitler.",
                "You know, once you get past __________, __________ ain't so bad.",
                "You Won't Believe These 15 Hilarious __________ Bloopers!",
                "You won't believe what's in my pussy. It's __________.",
                "You're in good hands with __________.",
                "Your father was a powerful wizard, Harry. Before he died, he left you something very precious: __________.",
                "Your persistence is admirable, my dear Prince. But you cannot win my heart with __________ alone.",
                "You're not going to believe this, but I'm you from the future! You've got to stop __________.",
                "You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon __________!"
            };
            foreach (var item in cards)
            {                
                int slots = FindSlots(item).Count();
                int pick=1;
                if (slots > pick)
                {
                    pick = slots;
                }
                BlackCard newCard = new BlackCard(id++, item,pick,pick);
                AllCards.Add(newCard);
            }

            Shuffle();
        }
    }
}
